# Generated by Django 5.1.2 on 2025-04-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0002_answerrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerrecord',
            name='audio_data',
            field=models.TextField(blank=True, null=True, verbose_name='用户录音数据'),
        ),
    ]
