# Generated by Django 5.1.2 on 2025-04-06 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0003_answerrecord_audio_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(choices=[('A', '键盘'), ('B', '手写'), ('C', '口述')], max_length=1)),
                ('interval', models.IntegerField(verbose_name='播放间隔（秒）')),
            ],
        ),
        migrations.AddField(
            model_name='answerrecord',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictation.practicesession'),
        ),
    ]
