# Generated by Django 5.1.2 on 2025-04-07 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0004_practicesession_answerrecord_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answerrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answerrecord',
            name='audio_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answerrecord',
            name='is_correct',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='answerrecord',
            name='user_input',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='interval',
            field=models.IntegerField(),
        ),
    ]
