# Generated by Django 5.1.2 on 2025-04-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0005_answerrecord_user_practicesession_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicesession',
            name='interval',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
